# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webapphbn1126

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webappacrhbn1126.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_33f1a353a8e24bd1a429ccf66460e65a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_94697e22f74a4c4b9d6ecc95ee23ca97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webappacrhbn1126.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_33f1a353a8e24bd1a429ccf66460e65a }}/webapphbn1126:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapphbn1126'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22decade8c7e4ba5a516814f68394dd5 }}
        images: 'webappacrhbn1126.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_33f1a353a8e24bd1a429ccf66460e65a }}/webapphbn1126:${{ github.sha }}'